apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: svtinfra-xml 
  namespace: prometheus 
data: 
  svtconnector.key: |- 
    R3eEo3h55iSucYSRrpSIZzo4LV7ydOuxK0TlW638flc=
  svtconnector.xml: |- 
    <data> 
      <username>SvtCollector@vsphere.local</username>
      <user>gAAAAABn6p9M4nlNVN27GKiijxeKDXmn_EWpyCvay2xH-AnrqFENshlpgEfh_u-V5OsPWL6p3-KdPN2XWIC7H2nsEk0-mg9nTFjsYGHjKrMD2RjX1Xtm4ps=</user>
      <password>gAAAAABn6p9MU8shpKVTmEv_BjWQqyTmTadIrUotYJ1OWCTEWxYg5mG6dL_kWpaed2dfpkfCcutLtnc89kUZ94Wk4J-ijjqsAg==</password>
      <ovc>10.0.44.33</ovc>
      <timerange>30</timerange>
      <resolution>SECOND</resolution>
      <monitoringintervall>30</monitoringintervall>
      <logfile>svtdemo.log</logfile>
      <port>9091</port>
      <monitor>fcn</monitor>
      <cluster></cluster>
      <limit>500</limit>
      <offset>-1</offset>
    </data>
